version: '3'

services:

  app:
    build:
      context: ./node
    networks:
      - node-nginx
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-nginx

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - node-nginx
    ports:
      - "8080:80"

volumes:
  data:

networks:
  node-nginx:
    driver: bridge
